// src/services/endpoints.js

export const endpoints = {
    categories: '/categories',
    news: '/news',
    single_news: '/single-news',
    about_list: '/about-universities',
    type_university: '/type-universities',
    single_university: '/single-universities',
    faculty: '/faculties',
    countAll: '/count-all',
    collaboration: '/portal-collaborations',
    collaborationType: '/collaboration-type',
    admission: '/admission',
    degrees: '/degrees',
    subjects: '/subjects',
    courses: '/courses',
    relatedCourses: '/related-courses',
    lessons: '/lessons',
    countView: '/count-view',
    search: '/search',
    search_news: '/search-news',
    academicCategories: '/academic-categories',
    academicFaculties: '/academic-faculties',
    academicFilters: '/academic-filters',
    academicResearches: '/academic-researches',
    mainExtra: '/main-extra',
    extraList: '/extras-list',
    extraDetail: '/extras-detail',
    viewDetail: '/view-detail',
    viewExtraDetail: '/view-extra-detail',
    major: '/majors',
    majorDetail: '/single-major',
    mainDegree: '/maindegrees',
    intensives: '/intensives',
    worldwideElibrary: '/worldwide-elibrary',
};

export const ENDPOINTS = endpoints;
export default endpoints;
